project/ratings/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, RadioField
from wtforms.validators import Length, DataRequired

CHOICES = [(str(i), str(i)) for i in range(1, 6)]


class RatingForm(FlaskForm):
    comment = TextAreaField('Comment', validators=[
        DataRequired(),
        Length(min=1, max=500, message="Comment must be between 1 nad 500 characters")
    ])
    rating = RadioField('Rating', choices=CHOICES, default='5')


class DeleteRatingForm(FlaskForm):
    pass

project/reviews/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, RadioField
from wtforms.validators import Length, DataRequired

CHOICES = [(str(i), str(i)) for i in range(1, 6)]


class ReviewForm(FlaskForm):
    comment = TextAreaField('Comment', validators=[
        DataRequired(),
        Length(min=1, max=500, message="Comment must be between 1 nad 500 characters")
    ])
    rating = RadioField('Rating', choices=CHOICES, default='5')


class DeleteReviewForm(FlaskForm):
    pass

project/__init__.py
import os

from dotenv import load_dotenv
from flask import Flask, render_template
from flask_session import Session
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt


load_dotenv()

session = Session()
db = SQLAlchemy()
bcrypt = Bcrypt()

# Check for environment variable
if not os.getenv("DATABASE_URL"):
    raise RuntimeError("DATABASE_URL is not set")

# Error handler


def page_not_found(e):
    return render_template('404.html'), 404


def create_app(script_info=None):

    app = Flask(__name__)

    # set config
    app_settings = os.getenv('APP_SETTINGS')
    app.config.from_object(app_settings)

    # set up extensions
    session.init_app(app)
    db.init_app(app)
    bcrypt.init_app(app)

    # Error handlers
    app.register_error_handler(404, page_not_found)

    # set up blueprints
    from project.books.routes import books_blueprint
    from project.auth.routes import auth_blueprint
    from project.reviews.routes import reviews_blueprint
    from project.api.routes import api_blueprint

    app.register_blueprint(books_blueprint)
    app.register_blueprint(auth_blueprint)
    app.register_blueprint(reviews_blueprint)
    app.register_blueprint(api_blueprint)

    @app.shell_context_processor
    def ctx():
        return {'app': app, 'db': db}

    return app

project/api/routes.py
from flask import Blueprint, jsonify, abort
from project import db

api_blueprint = Blueprint('api', __name__, url_prefix="/api")


@api_blueprint.errorhandler(404)
def not_found(error=None):
    data = {
        'status': 404,
        'message': 'Book not found.'
    }

    resp = jsonify(data)
    resp.status_code = 404

    return resp


@api_blueprint.route("/<isbn>", methods=['GET'])
def detail(isbn):
    try:
        book = db.session.execute(
            """SELECT books.isbn, books.title, books.author, books.year, 
                COUNT(reviews.rating) AS review_count, AVG(reviews.rating) AS average_score
                FROM books LEFT JOIN reviews
                ON books.id=reviews.book_id
                WHERE books.isbn=:isbn
                GROUP BY books.id""", {'isbn': isbn}).fetchone()

        data = {
            'isbn': book.isbn,
            'title': book.title,
            'author': book.author,
            'year': book.year,
            'review_count': book.review_count,
            'average_score': float(book.average_score or 0)
        }
        return jsonify(data)
    except:
        abort(404)

project/books/routes.py
import requests
from flask import Blueprint, render_template, session, abort, request, redirect, url_for, flash, current_app
from project import db
from utils.decorators import login_required
from project.reviews.forms import DeleteReviewForm

books_blueprint = Blueprint('books', __name__)


@books_blueprint.route("/")
def index():
    books = db.session.execute(
        "SELECT id, isbn, title, author, year FROM books").fetchall()
    return render_template('books/index.html', books=books)


@books_blueprint.route("/search", methods=['GET'])
@login_required
def search():
    query = request.args.get('q')
    if not query:
        flash("You must enter a search string.")
        return redirect(url_for('books.index'))

    page = request.args.get('page')
    page = int(page)

    page_count = db.session.execute("""
    SELECT CEILING(CAST(COUNT(*) AS DECIMAL)/5) FROM books WHERE tsv @@ plainto_tsquery(:query);
    """, {'query': query}).fetchone()[0]

    if page_count == 0:
        return abort(404)

    if page > page_count:
        page = page_count

    has_next = page < page_count
    has_previous = page > 1

    books = db.session.execute("""
    SELECT id, author, title, isbn                                                                                                                                  
    FROM books                                                                                                                                                                 
    WHERE tsv @@ plainto_tsquery(:query)                                                                                                                                   
    ORDER BY id ASC                                                                                                                                                            
    LIMIT :page_size offset ((:page - 1) * :page_size)
    """, {'query': query, 'page': page, 'page_size': 5}).fetchall()

    return render_template('books/search.html',
                           books=books,
                           page=page,
                           query=query,
                           has_next=has_next,
                           has_previous=has_previous)


@books_blueprint.route("/<isbn>")
@login_required
def detail(isbn):
    try:
        goodreads_key = current_app.config['GOODREADS_KEY']
        goodreads_response = requests.get(
            'https://www.goodreads.com/book/review_counts.json',
            params={'key': goodreads_key,
                    'isbns': isbn})

        goodreads_data = dict(goodreads_response.json())['books'][0]

    except:
        abort(404)

    book = db.session.execute(
        "SELECT id, isbn, title, author, year FROM books WHERE isbn=:isbn", {'isbn': isbn}).fetchone()

    if book is not None:
        data = {'book_id': book.id}

        reviews = db.session.execute("""
        SELECT users.username, reviews.rating, reviews.comment
        FROM reviews
        JOIN users on users.id=reviews.user_id
        WHERE reviews.book_id=:book_id
        """, data).fetchall()

        has_review = db.session.execute(
            "SELECT COUNT(*) FROM reviews WHERE book_id=:book_id AND user_id=:user_id",
            {'book_id': book['id'], 'user_id': session['user_id']}).fetchone()[0] > 0

        if has_review:
            form = DeleteReviewForm()
        else:
            form = None

        return render_template('books/detail.html', book=book, has_review=has_review, reviews=reviews, form=form, goodreads_data=goodreads_data)
    else:
        abort(404)

project/ratings/routes.py
from flask import Blueprint, render_template, redirect, flash, url_for, session, abort
from utils.decorators import login_required

from project.ratings.forms import RatingForm, DeleteRatingForm
from project import db


ratings_blueprint = Blueprint('ratings', __name__)


@ratings_blueprint.route("/<string:isbn>/ratings", methods=['GET', 'POST'])
@login_required
def create_rating(isbn):

    book_id = db.session.execute(
        "SELECT id FROM books WHERE isbn=:isbn", {'isbn': isbn}).fetchone()[0]
    user_id = session['user_id']

    has_rating = db.session.execute(
        "SELECT COUNT(*) FROM ratings WHERE book_id=:book_id AND user_id=:user_id",
        {'book_id': book_id, 'user_id': user_id}).fetchone()[0]

    if book_id < 1:
        abort(404)

    if has_rating > 0:
        flash("You have already left a rating.")
        return redirect(url_for('books.detail', isbn=isbn))

    form = RatingForm()

    if form.validate_on_submit():
        data = {
            'user_id': user_id,
            'comment': form.comment.data,
            'rating': form.rating.data,
            'book_id': book_id
        }

        db.session.execute(
            "INSERT INTO ratings (user_id, book_id, comment, rating) VALUES (:user_id, :book_id, :comment, :rating)", data)
        db.session.commit()

        flash("Comment has been added.")
        return redirect(url_for('books.detail', isbn=isbn))
    return render_template('ratings/create.html', form=form, isbn=isbn)


@ratings_blueprint.route("/<string:isbn>/ratings/update", methods=['GET', 'POST'])
@login_required
def update_rating(isbn):
    try:
        book_id = db.session.execute(
            "SELECT id FROM books WHERE isbn=:isbn", {'isbn': isbn}).fetchone()[0]
        user_id = session['user_id']
        data = {'book_id': book_id, 'user_id': user_id}

        rating = db.session.execute(
            "SELECT comment, rating FROM ratings WHERE book_id=:book_id AND user_id=:user_id",
            data).fetchone()

        if book_id is None:
            abort(404)

        form = RatingForm(obj=rating)

        if form.validate_on_submit():
            rating = form.rating.data
            comment = form.comment.data

            data['rating'] = rating
            data['comment'] = comment

            db.session.execute(
                "UPDATE ratings SET comment=:comment, rating=:rating WHERE book_id=:book_id AND user_id=:user_id",
                data)
            db.session.commit()

            flash("Your rating has been updated")
            return redirect(url_for('books.detail', isbn=isbn))

        return render_template('ratings/update.html', form=form, isbn=isbn)
    except:
        abort(404)


@ratings_blueprint.route("/<string:isbn>/ratings/delete", methods=['POST'])
@login_required
def delete_rating(isbn):
    user_id = session['user_id']
    book_id = db.session.execute(
        "SELECT id FROM books WHERE isbn=:isbn", {'isbn': isbn}).fetchone()[0]
    data = {
        'user_id': user_id,
        'book_id': book_id
    }

    form = DeleteRatingForm()

    if form.validate_on_submit():
        db.session.execute("DELETE FROM ratings WHERE user_id=:user_id AND book_id=:book_id",
                           data)
        db.session.commit()

        flash("The rating has been deleted.")

    else:
        flash("The rating could not be deleted.")

    return redirect(url_for('books.detail', isbn=isbn))

project/reviews/routes.py
from flask import Blueprint, render_template, redirect, flash, url_for, session, abort
from utils.decorators import login_required

from project.reviews.forms import ReviewForm, DeleteReviewForm
from project import db


reviews_blueprint = Blueprint('reviews', __name__)


@reviews_blueprint.route("/<string:isbn>/reviews", methods=['GET', 'POST'])
@login_required
def create_review(isbn):

    book_id = db.session.execute(
        "SELECT id FROM books WHERE isbn=:isbn", {'isbn': isbn}).fetchone()[0]
    user_id = session['user_id']

    has_review = db.session.execute(
        "SELECT COUNT(*) FROM reviews WHERE book_id=:book_id AND user_id=:user_id",
        {'book_id': book_id, 'user_id': user_id}).fetchone()[0]

    if book_id < 1:
        abort(404)

    if has_review > 0:
        flash("You have already left a review.")
        return redirect(url_for('books.detail', isbn=isbn))

    form = ReviewForm()

    if form.validate_on_submit():
        data = {
            'user_id': user_id,
            'comment': form.comment.data,
            'rating': form.rating.data,
            'book_id': book_id
        }

        db.session.execute(
            "INSERT INTO reviews (user_id, book_id, comment, rating) VALUES (:user_id, :book_id, :comment, :rating)", data)
        db.session.commit()

        flash("Comment has been added.")
        return redirect(url_for('books.detail', isbn=isbn))
    return render_template('reviews/create.html', form=form, isbn=isbn)


@reviews_blueprint.route("/<string:isbn>/reviews/update", methods=['GET', 'POST'])
@login_required
def update_review(isbn):
    try:
        book_id = db.session.execute(
            "SELECT id FROM books WHERE isbn=:isbn", {'isbn': isbn}).fetchone()[0]
        user_id = session['user_id']
        data = {'book_id': book_id, 'user_id': user_id}

        review = db.session.execute(
            "SELECT comment, rating FROM reviews WHERE book_id=:book_id AND user_id=:user_id",
            data).fetchone()

        if book_id is None:
            # abort(404)
            return "BOOK ID IS NONE"

        form = ReviewForm(obj=review)

        if form.validate_on_submit():
            rating = form.rating.data
            comment = form.comment.data

            data['rating'] = rating
            data['comment'] = comment

            db.session.execute(
                "UPDATE reviews SET comment=:comment, rating=:rating WHERE book_id=:book_id AND user_id=:user_id",
                data)
            db.session.commit()

            flash("Your review has been updated")
            return redirect(url_for('books.detail', isbn=isbn))

        return render_template('reviews/update.html', form=form, isbn=isbn)
    except:
        abort(404)


@reviews_blueprint.route("/<string:isbn>/reviews/delete", methods=['POST'])
@login_required
def delete_review(isbn):
    user_id = session['user_id']
    book_id = db.session.execute(
        "SELECT id FROM books WHERE isbn=:isbn", {'isbn': isbn}).fetchone()[0]
    data = {
        'user_id': user_id,
        'book_id': book_id
    }

    form = DeleteReviewForm()

    if form.validate_on_submit():
        db.session.execute("DELETE FROM reviews WHERE user_id=:user_id AND book_id=:book_id",
                           data)
        db.session.commit()

        flash("The review has been deleted.")

    else:
        flash("The review could not be deleted.")

    return redirect(url_for('books.detail', isbn=isbn))

project/templates/books/detail.html
{% extends 'base.html' %}

{% block title %}{{ book.title }}{% endblock  %}

{% block content %}
    {% include 'macros/_flash_messages.html' %}
    <div class="container">
        <div class="row mb-4">
            <div class="col-md-7">
                <div class="card  book-card text-center shadow-lg">
                    <div class="card-header">
                        <span class="lead">{{ book.title }}</span>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Author: {{ book.author }}</li>
                        <li class="list-group-item">Year: {{ book.year }}</li>
                        <li class="list-group-item">ISBN: {{ book.isbn }}</li>
                    </ul>
                    {% if  has_review %}
                    <div class="card-body">
                        <a href="{{ url_for('reviews.update_review', isbn=book.isbn)}}" class="card-link btn btn-primary mr-2 float-left">Update Review</a>
                        <form action="{{ url_for('reviews.delete_review', isbn=book.isbn)}}" method="post" class="float-right">
                            {{ form.hidden_tag() }}
                            <button class="btn btn-danger">Delete Review</button>
                        </form>
                    </div>
                    {% else %}
                    <div class="card-body rating-buttons text-center">
                        <a href="{{ url_for('reviews.create_review', isbn=book.isbn)}}" class="btn btn-primary">Write Review</a>
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-md-5 mt-4 mt-md-0">
                <div class="card text-center shadow-lg">
                    <div class="card-header">
                        Goodreads
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Average Rating: {{ goodreads_data['average_rating'] }}</li>
                        <li class="list-group-item">Total Ratings: {{ goodreads_data['work_ratings_count'] }}</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row mb-4">
            <div class="col">
                <div class="card">
                    <div class="card-header  text-center">
                        Ratings
                    </div>
                    {% if reviews %}
                    <ul class="list-group list-group-flush">
                    {% for review in reviews %}
                        <li class="list-group-item">{{ review.username }}
                            <span class="badge badge-primary mr-2 ml-2">{{ review.rating }}</span>
                            {{ review.comment }}
                        </li>
                    {% endfor %}
                    </ul>
                {% else %}
                <div class="card-body">
                    <p class="card-text text-center">There are no reviews.</p>
                </div>
                {% endif %}
                <div class="card-footer text-muted">
                </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

project/templates/books/index.html
{% extends 'base.html' %}

{% block title %}{{ message }}{% endblock  %}

{% block content %}
    <div class="index_messages">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-success m-2" role="alert">
                            {{ message}}
                        </div>
                    {% endfor %}
            {% endif %}
        {% endwith %}
    </div>
    <div class="jumbotron jumbotron-fluid hero mb-0">
        <div class="hero-text">
            {% if session['username'] %}
                <a href="#search" class="btn btn-warning">Search The Reviews</a>
            {% else %}
                <a href="{{ url_for("auth.login")}}" class="btn btn-warning">Log In to Participate</a>
            {% endif %}
        </div>
    </div>
{% endblock  %}

project/templates/books/search.html
{% extends 'base.html' %}

{% block title %}{{ message }}{% endblock  %}

{% block content %}
    {% include 'macros/_flash_messages.html' %}
    <div class="container mb-3">
        <li class="list-group">
            {% for book in books %}
                <li class="list-group-item"><i class="fa fa-book mr-3"></i><a href="{{ url_for('books.detail', isbn=book.isbn) }}">{{ book.title }}: {{ book.author }}</a> </li>
            {% endfor %}
        </li>
        <div class="text-center">
            {% if has_previous %}<a href="{{url_for('books.search')}}?q={{query}}&page={{page - 1}}" class=""><i class="fas fa-chevron-left fa-6x mr-4"></i></a>{% endif %}
            {% if has_next %}<a href="{{url_for('books.search')}}?q={{query}}&page={{page + 1}}" class=""><i class="fas fa-chevron-right fa-6x ml-4"></i></a>{% endif %}
        </div>
    </div>
{% endblock  %}

project/templates/books/temp_detail.html
{% extends 'base.html' %}

{% block title %}{{ book.title }}{% endblock  %}

{% block content %}
    {% include 'macros/_flash_messages.html' %}
    <div class="container mb-3">
        <div class="row mb-3">
            <div class="col-sm-7">
                <div class="book-card">
                    <div class="card-header">
                        {{ book.title }}
                    </div>
                    <ul>
                        <li class="text-center">Author: {{ book.author }}</li>
                        <li class="text-center">ISBN: {{ book.isbn }}</li>
                        <li class="text-center">Year: {{ book.year }}</li>
                    </ul>
                    {% if  has_rating %}
                    <div class="card-body rating-buttons">
                        <a href="{{ url_for('ratings.update_rating', isbn=book.isbn)}}" class="card-link btn btn-primary">Update Review</a>
                        <form action="{{ url_for('ratings.delete_rating', isbn=book.isbn)}}" method="post" class="float-right">
                            {{ form.hidden_tag() }}
                            <button class="btn btn-danger">Delete Review</button>
                        </form>
                    </div>
                    {% else %}
                    <div class="card-body rating-buttons text-center">
                        <a href="{{ url_for('ratings.create_rating', isbn=book.isbn)}}" class="btn btn-primary ">Write Review</a>
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-sm-5">
                <div class="goodreads-card">
                    <div class="card-header">
                        Goodreads
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text"></p>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="rating-card">
                <div class="card-header">
                        Ratings
                </div>
                {% if ratings %}
                    <ul>
                    {% for rating in ratings %}
                        <li>{{ rating.username }} <span class="badge badge-primary mr-2 ml-2">{{ rating.rating }}</span> {{ rating.comment }}</li>
                    {% endfor %}
                    </ul>
                {% else %}
                <div class="card-body">
                    <p class="card-text text-center">There are no ratings.</p>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}